pool:
  vmImage: Ubuntu 16.04
  
variables:
  BuildConfiguration: Release 
  ProjectName: PRZ.PushCenter.Web
  PackageName: pushcenter
  Revision: $[counter('versioncounter', 100000)]
  Version: 1.0.0

name: 1.0.0

steps:
- task: PowerShell@2
  displayName: Set Version
  inputs:
    targetType: inline
    script: |
      $v = "1.0.0-$(Get-Date -Format yyyyMMdd)-$(Revision)"
      Write-Host "##vso[task.setvariable variable=Version]$v"      
      
- task: PowerShell@2
  displayName: Set BuildNumber
  inputs:
    targetType: inline
    script: |
      $v = "$(Get-Date -Format yyyyMMdd)-$(Revision)-$($Env:BUILD_SOURCEBRANCHNAME)"
      Write-Host "##vso[build.updatebuildnumber]$v"
      
- task: DotNetCoreCLI@2
  displayName: Build and Publish
  inputs:
    command: publish
    projects: ./src/$(ProjectName)/$(ProjectName).csproj
    publishWebProjects: false
    arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: True
    versioningScheme: byEnvVar
    versionEnvVar: Version

- task: PublishBuildArtifacts@1
  displayName: Provide Build Artifacts
  inputs:
    artifactName: $(ProjectName)

- task: UniversalPackages@0
  displayName: Universal Publish
  condition: ne(variables['Build.Reason'], 'PullRequest')
  inputs:
    command: publish
    publishDirectory: $(Build.ArtifactStagingDirectory)
    vstsFeedPublish: feed
    vstsFeedPackagePublish: $(PackageName)
    versionOption: custom
    versionPublish: $(Version)
    packagePublishDescription: 
