pool:
  vmImage: Ubuntu 16.04
  
variables:
  BuildConfiguration: Release 
  ProjectName: PRZ.PushCenter.Web
  PackageName: pushcenter
  ContinuousVersion: 1
  Revision: $[counter('versioncounter', 100000)]
  Version: 0.0.0

name: 0.0.0

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      $v = "1.0.0-$(Get-Date -Format yyyyMMdd)-$($env:Revision)"
      $v2 = "$v-$($Env:BUILD_SOURCEBRANCHNAME)
      Write-Host "##vso[task.setvariable variable=ContinuousVersion]$v"
      Write-Host "##vso[build.updatebuildnumber]$v2"
      
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: ./src/$(ProjectName)/$(ProjectName).csproj
    publishWebProjects: false
    arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: $(ProjectName)

- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: $(Build.ArtifactStagingDirectory)
    vstsFeedPublish: feed
    vstsFeedPackagePublish: $(PackageName)
    versionOption: custom
    versionPublish: $(ContinuousVersion)
    packagePublishDescription: 
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
