pool:
  vmImage: Ubuntu 16.04
  
variables:
  BuildConfiguration: Release 
  ProjectName: PRZ.PushCenter.Web
  PackageName: pushcenter
  ContinuousVersion: 1
  Revision: $[counter('versioncounter', 100000)]
  Version: 0.0.0

name: 0.0.0

steps:
- task: PowerShell@2
  inputs:
    targetType: inline
    script: |
      $v1 = "$(Get-Date -Format yyyyMMdd)-$(Revision)"
      $v2 = "1.0.0-$(Get-Date -Format yyyyMMdd)-$(Revision)"
      $v3 = "$v1-$($Env:BUILD_SOURCEBRANCHNAME)
      Write-Host "##vso[task.setvariable variable=ContinuousVersion]$v2"
      Write-Host "##vso[build.updatebuildnumber]$v3"
      Write-Host "Variable: $v2 -> $($Env:ContinuousVersion)"
      
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    projects: ./src/$(ProjectName)/$(ProjectName).csproj
    publishWebProjects: false
    arguments: --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: True
    versioningScheme: byEnvVar
    versionEnvVar: ContinuousVersion

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: $(ProjectName)

- task: UniversalPackages@0
  displayName: Universal Publish
  inputs:
    command: publish
    publishDirectory: $(Build.ArtifactStagingDirectory)
    vstsFeedPublish: feed
    vstsFeedPackagePublish: $(PackageName)
    versionOption: custom
    versionPublish: $(ContinuousVersion)
    packagePublishDescription: 
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/'))
