// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PushCenter.Bll;

namespace PushCenter.Server.Migrations
{
    [DbContext(typeof(PushCenterDbContext))]
    partial class PushCenterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("PushCenter.Bll.Subscriptions.Subscription", b =>
            {
                b.Property<int>("Id")
                 .ValueGeneratedOnAdd()
                 .HasColumnType("integer")
                 .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Auth")
                 .HasColumnType("text");

                b.Property<string>("Endpoint")
                 .HasColumnType("text");

                b.Property<string>("P256Dh")
                 .HasColumnType("text");

                b.Property<int>("SubscriptionType")
                 .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("Subscriptions");
            });
#pragma warning restore 612, 618
        }
    }
}